### ISSUE TITLE
error using dashmips in ubuntu 18.04 with Anaconda python3.6

### ISSUE THREAD

**Issue by chakpongchung** [nbbeeken/dashmips#1]
```
cpchung:mips$ dashmips compile -f factorial.s 
Traceback (most recent call last):
  File "/home/cpchung/anaconda3/bin/dashmips", line 10, in <module>
    sys.exit(main())
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/dashmips/__main__.py", line 106, in main
    title='commands', dest='command', required=True
  File "/home/cpchung/anaconda3/lib/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
```
I ran 
```
pip install dataclasses
```

**Comment by nbbeeken** [comment]
Seems like the required keyword in the ArgumentPaser.add_subparsers method is a new addition in python 3.7: https://bugs.python.org/issue33109
I think I will remove support for 3.6 if I can't find a work around / fix. I hope a patch to 3.6 fixes this though! 🙂
